### ISSUE TITLE
🎂 [Release] Release v3.1.3-XXX - Fix Event Datetime, Rearrange Branding JS Files etc.

### ISSUE THREAD

**Issue by Tirokk** [Ocelot-Social-Community/stage.ocelot.social#5]
## 🎂 RELEASE

Release v3.1.3-XXX - Fix Event Datetime, Rearrange Branding JS Files etc.

### Todo

- [ ] rearrange branding JS files?
- [ ] add Neo4j configurtion `NEO4J_dbms_default__database` to the Kubernetes values of the Helm script
  - `DBMS_DEFAULT_DATABASE: "graph.db"`
- [ ] set new version and build number
